### ISSUE TITLE
Cannot add sensors

### ISSUE THREAD

**Issue by denperss11** [cyberjunky/home-assistant-brandweerrooster#15] opened 2021-01-07 01:29 UTC
Cannot add the following to the blueprint 

State to ex. Unlock a door, or garage door 
State to only enable light at a specific time. 
State when music is playing TTS get executed then all music stop and not playing again..

**Comment by denperss** [comment] 2021-01-15 12:42
???

**Comment by filmgarage** [comment] 2021-01-30 16:09
This is a duplicate of issue #17 Now closed

**Closed as completed by filmgarage** 2021-01-30 16:09 UTC
Labels: duplicate
